---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Services:
    - Vault:
        icon: https://vault.{{HOMEPAGE_VAR_DOMAIN_0}}/ui/favicon-c02e22ca67f83a0fb6f2fd265074910a.png
        href: https://vault.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://vault.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: Identity-based secrets management
    
    - Forgejo:
        icon: https://forgejo.org/favicon.ico
        href: https://forgejo.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://forgejo.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: Beyond coding. We forge.
        widget:
            type: gitea
            url: https://forgejo.{{HOMEPAGE_VAR_DOMAIN_0}}
            key: {{HOMEPAGE_VAR_FORGEJO_KEY}}

    - n8n:
        icon: https://n8n.io/favicon.ico
        href: https://n8n.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://n8n.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: AI Workflow Automation Platform & Tools

    # - Vaultwarden:
    #     icon: https://vaultwarden.{{HOMEPAGE_VAR_DOMAIN_0}}/images/favicon-32x32.png
    #     href: https://vaultwarden.{{HOMEPAGE_VAR_DOMAIN_0}}/
    #     siteMonitor: https://vaultwarden.{{HOMEPAGE_VAR_DOMAIN_0}}/
    #     description: An alternative server implementation of the Bitwarden Client API

    - Gramps Web:
        icon: https://www.grampsweb.org/favicon.ico
        href: https://tree.valan.rs/
        siteMonitor: https://tree.valan.rs/
        description: The free, open-source genealogy system for building your family tree

- Infrastructure:
    - Dockhand:
        icon: https://dockhand.{{HOMEPAGE_VAR_DOMAIN_0}}/favicon-32x32.png
        href: https://dockhand.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://dockhand.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: Modern Docker Management Application

    - Beszel:
        icon: https://beszel.dev/icon.svg
        href: https://beszel.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://beszel.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: Simple, lightweight server monitoring

    - Technitium:
        icon: https://technitium.com/img/logo25x25.png
        href: https://technitium.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://technitium.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: An Open Source DNS Server For Privacy & Security
        widget:
            type: technitium
            url: https://technitium.{{HOMEPAGE_VAR_DOMAIN_0}}
            key: {{HOMEPAGE_VAR_TECHNITIUM_KEY}}
            fields: ["totalQueries", "totalAuthoritative", "totalBlocked", "totalServerFailure"]

    - Traefik:
        icon: https://traefik.io/favicon.svg
        href: https://traefik.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://traefik.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: The Cloud Native Application Proxy
        widget:
            type: traefik
            url: https://traefik.{{HOMEPAGE_VAR_DOMAIN_0}}/

    - Grafana:
        icon: https://grafana.{{HOMEPAGE_VAR_DOMAIN_0}}/public/build/img/fav32.png
        href: https://grafana.{{HOMEPAGE_VAR_DOMAIN_0}}/
        siteMonitor: https://grafana.{{HOMEPAGE_VAR_DOMAIN_0}}/
        description: Full-stack observability for the agentic era

    - Minecraft:
        icon: https://www.minecraft.net/etc.clientlibs/minecraftnet/clientlibs/clientlib-site/resources/favicon-96x96.png
        widget:
            type: minecraft
            url: udp://100.76.87.226:25565

- External:
    - Cloudflare:
        icon: https://dash.cloudflare.com/favicon.ico
        href: https://dash.cloudflare.com/
        description: Connect, protect, and build everywhere

    - Netbird:
        icon: https://app.netbird.io/favicon.ico
        href: https://app.netbird.io/
        description: Mesh VPN

    - OCI:
        icon: https://www.oracle.com/asset/web/favicons/favicon-32.png
        href: https://www.oracle.com/cloud/
        description: Oracle Cloud Infrastructure

    - Google Cloud:
        icon: https://ssl.gstatic.com/pantheon/images/favicon/default.png
        href: https://console.cloud.google.com/
        description: Cloud Computing Services

    - AlwaysData:
        icon: https://static.alwaysdata.com/media/reseller/1/theme/favicon_kfxZA8s.png
        href: https://admin.alwaysdata.com/
        description: the European Cloud

    - Supabase:
        icon: https://supabase.com/dashboard/favicon/apple-icon-57x57.png
        href: https://supabase.com/dashboard
        description: The Postgres Development Platform

    - Aiven:
        icon: https://aiven.io/favicons/favicon-32x32.png
        href: https://aiven.io/
        description: Your AI-ready Open Source Data Platform

    - CloudAMQP:
        icon: https://www.cloudamqp.com/favicon.ico
        href: https://www.cloudamqp.com/
        description: Queue starts here.

    - Grafana:
        icon: https://grafana.com/static/assets/img/fav32.png
        href: https://zaharsk.grafana.net/
        description: The open and composable observability platform

    - FolderFort:
        icon: https://www.folderfort.com/wp-content/uploads/2024/02/favicon-100x100.png
        href: https://eu2.folderfort.com/
        description: Fast, affordable cloud storage
    
    - OysterVPN:
        icon: https://oystervpn.com/favicon.png
        href: https://oystervpn.com/auth/login/
        description: Privacy For Your Digital Life