name: postgres
services:
  pgadmin:
    image: dpage/pgadmin4

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config_local.py:/pgadmin4/config_local.py:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"

    ports:
      - '0.0.0.0:8080:80'
    
    restart: unless-stopped
    
    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - '0.0.0.0:5432:5432'

    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    cap_drop:
      - ALL

    cap_add:
      - CHOWN

    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
  pgadmin_data:
