services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
      - GF_SERVER_ROOT_URL=https://grafana.unco.games
    ports:
      - '3000:3000'
    volumes:
      - 'storage:/var/lib/grafana'
volumes:
  storage: {}