name: monitoring

services:
  grafana:
    image: grafana/grafana

    volumes:
      - gf_storage:/var/lib/grafana
      - ./conf/custom.ini:/usr/share/grafana/conf/custom.ini

    environment:
      GF_LOG_LEVEL: "debug"

      GF_SERVER_ROOT_URL: "https://grafana.unco.games"

      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: "Vault"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email groups"

      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://vault.unco.games/ui/vault/identity/oidc/provider/default/authorize"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://vault.unco.games/v1/identity/oidc/provider/default/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://vault.unco.games/v1/identity/oidc/provider/default/userinfo"

      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: true
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'grafana_admins') && 'GrafanaAdmin' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: true

    ports:
      - '0.0.0.0:3000:3000'

    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          editable: false
        EOF
        /run.sh

    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

  loki:
    image: grafana/loki:latest

    volumes:
      - loki_storage:/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml

    ports:
      - '0.0.0.0:3100:3100/tcp'

    command: -config.file=/etc/loki/local-config.yaml

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

  prometheus:
    image: prom/prometheus:latest

    volumes:
      - prom_storage:/prometheus
      - ./prom-config.yaml:/etc/prometheus/prometheus.yml

    ports:
      - '0.0.0.0:9090:9090/tcp'

    command:
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

volumes:
  loki_storage: {}
  prom_storage: {}
  gf_storage: {}
