services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    ports:
      - '3000:3000'
    volumes:
      - 'storage:/var/lib/grafana'
      - './conf/custom.ini:/usr/share/grafana/conf/custom.ini'
volumes:
  storage: {}