services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    cap_add:
      - IPC_LOCK

    environment:
      VAULT_API_ADDR: "https://vault.unco.games"
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_CLUSTER_ADDR: "http://100.76.122.97:8201"

    ports:
      - "8200:8200"
      - "8201:8201"

    command:
      - vault
      - server
      - -config=/vault/config/vault.hcl

    volumes:
      - ./config:/vault/config
      - logs:/vault/logs
      - file:/vault/file

    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8200/v1/sys/health || exit 1" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  logs:
  file: