---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Enable unattended upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";

- name: Configure unattended upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50-unattended-upgrades
    mode: "0644"
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
      };

      Unattended-Upgrade::AutoFixInterruptedDpkg "true";

      Unattended-Upgrade::Remove-Unused-Dependencies "true";

      Unattended-Upgrade::Automatic-Reboot "true";

      Unattended-Upgrade::Automatic-Reboot-Time "02:45";
