services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: "https://beszel.unco.games"
      USER_CREATION: true

    ports:
      - 8090:8090

    volumes:
      - beszel_data:/beszel_data

    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 5s # Check 5 seconds after the container starts
      interval: 120s # Then check every 120 seconds after that

volumes:
  beszel_data:
