---
- name: Setup common software and parameters
  hosts: ubuntu
  become: true

  vars_files:
    - /dev/shm/ansible.vars.yml

  roles:
    - install_common_pckgs
    - install_netbird
    - configure_netbird
    - install_docker
