[log]
level = debug

[server]
root_url = https://grafana.unco.games

[auth.generic_oauth]
enabled = true

name = "Vault"
scopes = openid profile email groups
; client_id = <client id>
; client_secret = <client secret>

auth_url = https://vault.unco.games/ui/vault/identity/oidc/provider/default/authorize
token_url = https://vault.unco.games/v1/identity/oidc/provider/default/token
api_url = https://vault.unco.games/v1/identity/oidc/provider/default/userinfo

allow_assign_grafana_admin = true
role_attribute_path = "contains(groups[*], 'grafana_admins') && 'GrafanaAdmin' || 'Viewer'"
role_attribute_strict = true