name: homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest

    volumes:
      # Make sure your local config directory exists
      - ./config:/app/config
      # (optional) For docker integrations
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_ALLOWED_HOSTS: homepage.${HOMEPAGE_VAR_DOMAIN_0}
      HOMEPAGE_VAR_FORGEJO_KEY: ${HOMEPAGE_VAR_FORGEJO_KEY}
      HOMEPAGE_VAR_TECHNITIUM_KEY: ${HOMEPAGE_VAR_TECHNITIUM_KEY}
      HOMEPAGE_VAR_DOMAIN_0: ${HOMEPAGE_VAR_DOMAIN_0}
      HOMEPAGE_VAR_DOMAIN_1: ${HOMEPAGE_VAR_DOMAIN_1}
      HOMEPAGE_VAR_DOMAIN_2: ${HOMEPAGE_VAR_DOMAIN_2}
      HOMEPAGE_VAR_3XUI_PATH_NL: ${HOMEPAGE_VAR_3XUI_PATH_NL}
      HOMEPAGE_VAR_3XUI_PATH_RU: ${HOMEPAGE_VAR_3XUI_PATH_RU}
      HOMEPAGE_VAR_QB_USERNAME: ${HOMEPAGE_VAR_QB_USERNAME}
      HOMEPAGE_VAR_QB_PASSWORD: ${HOMEPAGE_VAR_QB_PASSWORD}

    ports:
      - "0.0.0.0:3001:3000"

    restart: unless-stopped

    # https://github.com/gethomepage/homepage/discussions/6544#discussioncomment-16510143
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          http://127.0.0.1:3000/api/healthcheck,
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # cap_drop:
    #   - ALL

    # security_opt:
    #   - no-new-privileges:true
