name: forgejo
services:
  server:
    image: codeberg.org/forgejo/forgejo:15

    container_name: forgejo

    volumes:
      - data:/data
      - /etc/localtime:/etc/localtime:ro

    environment:
      FORGEJO____APP_NAME: "Unco Games"

      FORGEJO__server__ROOT_URL: "https://forgejo.unco.games/"
      FORGEJO__server__START_SSH_SERVER: true
      FORGEJO__server__SSH_DOMAIN: "forgejo.unco.games"
      FORGEJO__server__SSH_PORT: 2201
      FORGEJO__server__SSH_LISTEN_PORT: 2201

      FORGEJO__oauth2_client__ACCOUNT_LINKING: "auto"
      FORGEJO__oauth2_client__ENABLE_AUTO_REGISTRATION: true
      FORGEJO__oauth2_client__OPENID_CONNECT_SCOPES: "email profile groups"
      FORGEJO__oauth2_client__REGISTER_EMAIL_CONFIRM: false
      FORGEJO__oauth2_client__USERNAME: "nickname"

      FORGEJO__openid__ENABLE_OPENID_SIGNIN: false
      FORGEJO__openid__ENABLE_OPENID_SIGNUP: false

      FORGEJO__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      FORGEJO__service__DISABLE_REGISTRATION: true
      FORGEJO__service__ENABLE_INTERNAL_SIGNIN: false
      FORGEJO__service__SHOW_REGISTRATION_BUTTON: false

      FORGEJO__log__LEVEL: "debug"

    ports:
      - '0.0.0.0:2201:2201'
      - '0.0.0.0:3001:3000'

    restart: unless-stopped

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

volumes:
  data: {}
