http:
  services:
    beszel:
      loadBalancer:
        servers:
          - url: http://100.76.112.49:8090
  
  routers:
    beszel-webhook:
      entryPoints:
        - https-ep
      rule: 'Host(`beszel.{{ env "DOMAIN_1" }}`) && PathPrefix(`/api`)'
      service: beszel
      middlewares:
        - securityHeaders

    beszel-private:
      entryPoints:
        - https-ep
      rule: 'Host(`beszel.{{ env "DOMAIN_1" }}`)'
      service: beszel
      middlewares:
        - securityHeaders
        - privateAccess
