http:
  services:
    dockhand:
      loadBalancer:
        servers:
          - url: http://100.76.122.97:3000
  
  routers:
    dockhand-webhook:
      entryPoints:
        - https-ep
      rule: 'Host(`dockhand.{{ env "DOMAIN_1" }}`) && PathPrefix(`/api/git/stacks`)'
      service: dockhand
      middlewares:
        - securityHeaders

    dockhand-private:
      entryPoints:
        - https-ep
      rule: 'Host(`dockhand.{{ env "DOMAIN_1" }}`)'
      service: dockhand
      middlewares:
        - securityHeaders
        - privateAccess
