tcp:
  services:
    forgejo-ssh:
      loadBalancer:
        servers:
          - address: 100.76.87.226:2201
  routers:
    forgejo-ssh:
      entryPoints:
        - ssh-forgejo-ep
      rule: HostSNI(`*`)
      service: forgejo-ssh
