http:
  services:
    forgejo:
      loadBalancer:
        servers:
          - url: http://100.76.112.49:3001
  
  routers:
    forgejo:
      entryPoints:
        - https-ep
      rule: "Host(`forgejo.unco.games`)"
      service: forgejo
      middlewares:
        - securityHeaders

tcp:
  services:
    forgejo-ssh:
      loadBalancer:
        servers:
          - address: 100.76.112.49:2201
  routers:
    forgejo-ssh:
      entryPoints:
        - ssh-forgejo-ep
      rule: "HostSNI(`*`)"
      service: forgejo-ssh

  