http:
  serversTransports:
    forgejo-transport:
      maxIdleConnsPerHost: 100
      forwardingTimeouts:
        dialTimeout: 30s
        responseHeaderTimeout: 10m
        idleConnTimeout: 10m

  services:
    forgejo:
      loadBalancer:
        serversTransport: forgejo-transport
        servers:
          - url: http://100.76.112.49:3001

  routers:
    forgejo:
      entryPoints:
        - https-ep
      rule: 'Host(`forgejo.{{ env "DOMAIN_1" }}`)'
      service: forgejo
      middlewares:
        - securityHeaders
        - privateAccess
