http:
  services:
    grampsweb:
      loadBalancer:
        servers:
          - url: http://100.76.228.137:5000
  
  routers:
    grampsweb:
      entryPoints:
        - https-ep
      rule: Host(`tree.{{ env "DOMAIN_1" }}`)
      service: grampsweb
      middlewares:
        - securityHeaders
