http:
  services:
    homepage:
      loadBalancer:
        servers:
          - url: http://100.76.122.97:3001

  routers:
    homepage-private:
      entryPoints:
        - https-ep
      rule: Host(`homepage.{{ env "DOMAIN_0" }}`)
      service: homepage
      middlewares:
        - securityHeaders
        - privateAccess
