tcp:
  services:
    minecraft:
      loadBalancer:
        servers:
          - address: 100.76.87.226:25565
  routers:
    minecraft:
      entryPoints:
        - minecraft-ep
      rule: HostSNI(`*`)
      service: minecraft
