http:
  services:
    n8n:
      loadBalancer:
        servers:
          - url: http://100.76.87.226:5678
  
  routers:
    n8n-private:
      entryPoints:
        - https-ep
      rule: 'Host(`n8n.{{ env "DOMAIN_1" }}`)'
      service: n8n
      middlewares:
        - securityHeaders
        - privateAccess

    n8n-webhook:
      entryPoints:
        - https-ep
      rule: 'Host(`n8n.{{ env "DOMAIN_1" }}`) && (PathPrefix(`/webhook`) || PathPrefix(`/webhook-test`))'
      service: n8n
      middlewares:
        - securityHeaders
  