http:
  services:
    n8n:
      loadBalancer:
        servers:
          - url: http://100.76.87.226:5678
  
  routers:
    n8n:
      entryPoints:
        - https-ep
      rule: "Host(`n8n.unco.games`)"
      service: n8n
      middlewares:
        - securityHeaders
        - privateAccess
  