http:
  services:
    technitium:
      loadBalancer:
        servers:
          - url: http://100.76.122.97:5380
  
  routers:
    technitium-private:
      entryPoints:
        - https-ep
      rule: 'Host(`technitium.{{ env "DOMAIN_1" }}`)'
      service: technitium
      middlewares:
        - securityHeaders
        - privateAccess
