http:
  services:
    vault:
      loadBalancer:
        servers:
          - url: http://100.76.122.97:8200
  
  routers:
    vault:
      entryPoints:
        - https-ep
      rule: 'Host(`vault.{{ env "DOMAIN_1" }}`)'
      service: vault
      middlewares:
        - securityHeaders
