name: traefik
services:
  traefik:
    image: traefik:latest

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./certs:/etc/traefik/certs:rw
      - ./logs:/logs:rw

    environment:
      - TZ=Europe/Belgrade
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - DOMAIN_0=${DOMAIN_0}
      - DOMAIN_1=${DOMAIN_1}

    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:2201:2201/tcp' # Forgejo ssh 
      - '127.0.0.1:8080:8080' # Traefik Dashboard and healthcheck
      - '0.0.0.0:25565:25565/tcp' # Minecraft

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/ping" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

    labels:
      - traefik.enable=true

      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_0}`)
      - traefik.http.routers.dashboard.entrypoints=https-ep
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.service=api@internal
      # - traefik.http.routers.dashboard.middlewares=privateAccess@file

      - traefik.entryPoints.https-ep.http.tls.domains[0].main=${DOMAIN_0}
      - traefik.entryPoints.https-ep.http.tls.domains[0].sans=*.${DOMAIN_0}
      - traefik.entryPoints.https-ep.http.tls.domains[1].main=${DOMAIN_1}
      - traefik.entryPoints.https-ep.http.tls.domains[1].sans=*.${DOMAIN_1}

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true
