services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080 # Traefik Dashboard and healthcheck
      - 2201:2201/tcp # Forgejo ssh 
      # - 25565:25565/tcp # Minecraft

    environment:
      - TZ=Europe/Belgrade
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - DOMAIN_1=${DOMAIN_1}
      - DOMAIN_2=${DOMAIN_2}
      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./certs:/etc/traefik/certs:rw
      - ./logs:/logs:rw

    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_1}`)
      - traefik.http.routers.dashboard.entrypoints=https-ep
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=privateAccess@file

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/ping"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
