name: kopia

services:
  kopia:
    image: kopia/kopia:latest

    volumes:
      - config:/app/config
      - cache:/app/cache
      - logs:/app/logs
      - tmp:/tmp

    environment:
      TZ: Europe/Belgrade

    ports:
      - '0.0.0.0:51515:51515'

    command:
      - server
      - start
      - --insecure
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      # - --server-username=${KOPIA_UI_USER}
      - --server-username=admin
      # - --server-password=${KOPIA_UI_PASSWORD}
      - --server-password=admin

    restart: unless-stopped

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

volumes:
  config: {}
  cache: {}
  logs: {}
  tmp: {}
